In [7]:
import pandas as pd

# 1. Import data
# load logging.csv into a pandas dataframe with ansii encoding and no header
df = pd.read_csv('logging.csv', encoding='ansi', header=None)
# name first column "Prozess"
df.columns = ['process',
              'loop_number_of_date',
              'logging_date',
              'logging_time',
              'RAM_usage_KB',
              'user']

In [8]:
# 2. Data transformation
# remove last 2 characters from date
df['logging_date'] = df['logging_date'].str[:-2]
# remove last 2 characters from Ram usage
df['RAM_usage_KB'] = df['RAM_usage_KB'].str[:-2]
# replace wrong Ä character in user column
df['user'] = df['user'].str.replace('Ž', 'Ä')
# remove dot in ram usage
df['RAM_usage_KB'] = df['RAM_usage_KB'].str.replace('.', '')
# cast ram usage to int
df['RAM_usage_KB'] = df['RAM_usage_KB'].astype(int)

C:\Users\vbu2985\AppData\Local\Temp\8\ipykernel_6544\2608891648.py:9: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['RAM_usage_KB'] = df['RAM_usage_KB'].str.replace('.', '')

In [9]:
df

,process,loop_number_of_date,logging_date,logging_time,RAM_usage_KB,user
0,System Idle Process,1,13.03.2023,13:57,8,NT-AUTORITÄT\SYSTEM
1,System,1,13.03.2023,13:57,144,Nicht zutreffend
2,Registry,1,13.03.2023,13:57,198032,NT-AUTORITÄT\SYSTEM
3,smss.exe,1,13.03.2023,13:57,1124,NT-AUTORITÄT\SYSTEM
4,csrss.exe,1,13.03.2023,13:57,6476,NT-AUTORITÄT\SYSTEM
...,...,...,...,...,...,...
463,cmd.exe,2,13.03.2023,13:58,3720,BKKVBU\vbu2985
464,svchost.exe,2,13.03.2023,13:58,6444,NT-AUTORITÄT\SYSTEM
465,cmd.exe,2,13.03.2023,13:58,4672,BKKVBU\vbu2985
466,conhost.exe,2,13.03.2023,13:58,18264,BKKVBU\vbu2985
467,tasklist.exe,2,13.03.2023,13:58,8616,BKKVBU\vbu2985

In [10]:
# 3 grouping data
# group by process and user
df_grouped = df.groupby(['user',
                         'process',
                         'loop_number_of_date',
                         'logging_date'])
df_grouped = df_grouped.agg({'logging_time':'min',
                            'RAM_usage_KB':'sum'})
df_grouped

                                                                         logging_time  \
user                 process            loop_number_of_date logging_date
BKKVBU\vbu1385       DiasBackend.exe    1                   13.03.2023          13:57
                                        2                   13.03.2023          13:58
                     RuntimeBroker.exe  1                   13.03.2023          13:57
                                        2                   13.03.2023          13:58
                     SCNotification.exe 1                   13.03.2023          13:57
...                                                                               ...
Window Manager\DWM-4 dwm.exe            2                   13.03.2023          13:58
Window Manager\DWM-6 dwm.exe            1                   13.03.2023          13:57
                                        2                   13.03.2023          13:58
Window Manager\DWM-8 dwm.exe            1                   13.03.2023          13:57
                                        2                   13.03.2023          13:58

                                                                          RAM_usage_KB
user                 process            loop_number_of_date logging_date
BKKVBU\vbu1385       DiasBackend.exe    1                   13.03.2023          879300
                                        2                   13.03.2023          879652
                     RuntimeBroker.exe  1                   13.03.2023           47492
                                        2                   13.03.2023           47492
                     SCNotification.exe 1                   13.03.2023           44940
...                                                                                ...
Window Manager\DWM-4 dwm.exe            2                   13.03.2023           88420
Window Manager\DWM-6 dwm.exe            1                   13.03.2023           74956
                                        2                   13.03.2023           74956
Window Manager\DWM-8 dwm.exe            1                   13.03.2023           88348
                                        2                   13.03.2023           88348

[240 rows x 2 columns]